### ISSUE TITLE
Export to static web page

### ISSUE THREAD

**Issue by shial4** [SwiftWebUI/SwiftWebUI#48] opened 2019-10-22 04:40 UTC
Hi, 

I was thinking if we could achieve something like static web page result. 
As a product generated after build/run in the Xcode. What do you think? 

If you think it is possible I am more than happy to help :) 
Would need your help to direct me where to look, focus at. 

Cheers,
Shial

**Comment by shial4** [comment] 2019-10-22 08:39
got ya.
I've just read this: 
https://github.com/SwiftWebUI/SwiftWebUI/issues/36

What about binding and context management thru javascript? 
SwiftUI views could generate HTML + CSS predefine components, bindings and logic would generate whole web interfaces. Could use for it (hyperapp)[https://hyperapp.dev] micro framework. 

The output would be reactive web app generated from SwiftUI code. 
As you said though. Good for another project. 


To continue struggle. What about HTTP server injection. So people could use it inside Vapor, Kitura, Perfect or any other HTTP server?

**Comment by helje5** [comment] 2019-10-22 08:52
Yes, this is a dupe of #36 . While I _am_ tempted to port StaticCMS ideas to Swift in combination with SwiftUI, I think it absolutely makes sense to wait what @JohnSundell comes up with. His stuff must be close to release, and who knows, maybe it is what we want :-)  ...
The general flaw w/ using Swift for this kind of stuff is the abysmal speed of the compiler. But maybe that can be fixed in the midterm using Previews like Fix&Continue features. They said they are going to use this for more within Xcode ...

The way SwiftWebUI is build, it is solely a toy project which doesn't make sense in combination w/ other frameworks. Nor on its own :-) This specific thing would be more interesting once we have Swift WASM and this thing can run client side.
BTW: I rather expect those other frameworks to provide SwiftUI like APIs on their own.

**Closed by helje5** 2019-10-22 08:53 UTC
