### ISSUE TITLE
`Spacer` not same as `SwiftUI`

### ISSUE THREAD

**Issue by josercc** [swiftwebui/SwiftWebUI#37] opened 2019-07-07 03:05 UTC
```swift
HStack {
                Text("\(index)")
                Spacer()
                Button(action: {
                    self.index += 1
                }) {
                    Text("Cilie Me")
                }
            }
```

`Text` and `Button` not in Web Content `Left` And `Right` .Now in all Left Offset

**Comment by helje5** [comment] 2019-07-07 11:41
That's a dupe of Issue #5 We'd probably need some Flexbox export to discuss how to consistently map SwiftUI layout to Flexbox/CSS.

SwiftWebUI tries to make `Spacer` work and expand in some places, but that doesn't work in any case.

Your issue is that the outer containers don't take the full width. You can play w/ `VStack(alignment: .stretch)`. The Tinker2 example has some samples showing what you try to do.

**Closed by helje5** 2019-07-07 11:41 UTC

**Comment by josercc** [comment] 2019-07-07 12:06
Tanks
